-- MySQL Script generated by MySQL Workbench
-- Sat Aug 13 09:32:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema peluqueria_canina
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `peluqueria_canina` ;

-- -----------------------------------------------------
-- Schema peluqueria_canina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `peluqueria_canina` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `peluqueria_canina` ;

-- -----------------------------------------------------
-- Table `peluqueria_canina`.`dueno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peluqueria_canina`.`dueno` (
  `DNI` INT NOT NULL,
  `Nombre` VARCHAR(50) NULL DEFAULT NULL,
  `Apellido` VARCHAR(50) NULL DEFAULT NULL,
  `Telefono` INT NULL DEFAULT NULL,
  `Direccion` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `peluqueria_canina`.`perro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peluqueria_canina`.`perro` (
  `ID_perro` INT NOT NULL,
  `Nombre` VARCHAR(50) NULL DEFAULT NULL,
  `Fecha_nac` DATE NULL DEFAULT NULL,
  `Sexo` VARCHAR(50) NULL DEFAULT NULL,
  `DNI_dueno` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID_perro`),
  CONSTRAINT `fk`
    FOREIGN KEY (`DNI_dueno`)
    REFERENCES `peluqueria_canina`.`dueno` (`DNI`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_idx` ON `peluqueria_canina`.`perro` (`DNI_dueno` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `peluqueria_canina`.`historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peluqueria_canina`.`historial` (
  `ID_historial` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NULL DEFAULT NULL,
  `Perro` INT NULL DEFAULT NULL,
  `Descripcion` VARCHAR(200) NULL DEFAULT NULL,
  `Monto` DECIMAL(10,0) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_historial`),
  CONSTRAINT `fk__`
    FOREIGN KEY (`Perro`)
    REFERENCES `peluqueria_canina`.`perro` (`ID_perro`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk___idx` ON `peluqueria_canina`.`historial` (`Perro` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
INSERT INTO dueno (DNI, Nombre, Apellido, Telefono, Direccion) VALUES 
('33724046','Fabio','Luna','654123','Ponton Rio Negro 614');

INSERT INTO dueno (DNI, Nombre, Apellido, Telefono, Direccion) VALUES 
('35692059','Rocio','Perez','554855','Rivadavia 51');

INSERT INTO perro (ID_perro, Nombre, Fecha_nac, Sexo, DNI_dueno) VALUES
( '2','hercules', '2022-5-24', 'macho', '33724046');

INSERT INTO perro (ID_perro, Nombre, Fecha_nac, Sexo, DNI_dueno) VALUES
( '3','paloma', '2021-01-14', 'hembra', '35692059');

update perro set Fecha_nac = '2022-05-20' where ID_perro=2;

select p.Nombre, d.Nombre from perro as p inner join dueno as d on p.DNI_dueno = d.DNI WHERE d.Nombre='Pedro';
